### ISSUE TITLE
add image based environment sampling

### ISSUE THREAD

**Issue by nathanielfernandes** [Ray-Traycer/Tracer#2]
resources:
http://igorsklyar.com/system/documents/papers/4/fiscourse.comp.pdf
https://github.com/Drummersbrother/raytracing-in-one-weekend/blob/master/pdf.h#L95

inside:
world/hdri.rs

**Comment by fabyanMikhael** [comment]
😴🛌

**Comment by fabyanMikhael** [comment]
doesn't even work 🛌
